---
title: "Monthly_Sales"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(gridExtra)
library(patchwork)
```


```{r}
sales <- readxl::read_xlsx("storytelling_data/Practice_2021_10.xlsx") %>% 
  pivot_longer(-month, names_to = "year", values_to = "sales") %>% 
  relocate(year)
```

# If the sales gets a peak in Jul 

```{r}
p <- sales %>% 
  ggplot(aes(month, sales, group = year)) +
  geom_line(aes(color = ifelse(month %in% c(6, 7), "red", "grey"))) +
  geom_point(color = ifelse(sales$month == 7, "#FF8040", "grey80")) + 
  scale_color_manual(values = c("grey80", "#FF8040")) +
  scale_x_continuous(breaks = seq(1,12,1)) +
  scale_y_continuous(labels = scales::comma_format(prefix = "$")) +
  annotate(geom = "richtext", x = 8.5, y = 520000,
           label = "<span style='font-size:9pt; color:grey50'>There's a upward jump <br> in <span style='color:#FF8040; font-size:12pt'>**July**</span> and the sales <br> quickly decreases after <br>that.</span>",
           fill = NA, label.color = NA, hjust = 0) +  
  labs(title = "<span style = 'color:grey50'>Average Monthly Home Sales of Halmiton: 2019-2021</span>",
       subtitle = "**IS THERE A SEASONAL TREND?**") +
  theme(axis.ticks = element_blank(),
        axis.line = element_line(color = "grey80"),
        panel.background = element_blank(),
        legend.position = "none",
        plot.title = element_markdown(),
        plot.title.position = "plot",
        plot.subtitle = element_markdown(),
        axis.title.x = element_text(hjust = 0, color = "grey50"),
        axis.title.y = element_text(hjust = 1, color = "grey50"),
        axis.text = element_text(color = "grey50"))
ggsave("practice_2021_10.png", plot = p)
```




```{r}
sales_prepared <- sales %>% 
  arrange(year, month) %>% 
  mutate(profit = (sales - lag(sales)) / lag(sales)) %>% 
  add_row(year = NA, .before = 13) %>% 
  add_row(year = NA, .before = 26) %>% 
  mutate(number = row_number()) 

p1 <- sales_prepared %>% 
  ggplot(aes(number, sales)) +
  geom_line(color = "grey50", size = 1, alpha = 0.5) +
  geom_point(aes(color = profit)) +
  scale_color_gradient2(high = "black",
                        mid = "grey80",
                        low = "red",
                        breaks = c(-0.0566, 0, 0.0944),
                        labels = c("-5.7%", 0, "9.4%"),
                        limits = c(-0.0566, 0.0944),
                        guide = guide_colorbar(barwidth = 5, barheight = 0.7, title.position = "top", title = "MoM change", frame.colour = "grey50")) +
  scale_x_continuous(limits = c(0, 36),
                     expand = c(0, 0)) +
  scale_y_continuous(limits = c(400000, 620000), labels = scales::comma_format(prefix = "$"), 
                     breaks = seq(400000, 620000, 100000)) +
  annotate("segment", y = 610000, yend = 610000, x = 0, xend = 36, color = "grey70") +
  annotate("richtext", y = 617000, x = c(6, 18, 30), label = c("<span style='color:grey70'>2019</span>", "<span style='color:grey70'>2020</span>", "<span style='color:grey70'>2021</span>"), fill = NA, label.color = NA) +
  annotate("segment", y = 500000, yend = 500000, x = 0, xend = 36, color = "grey70", linetype = 2) +
  annotate("richtext", y = 580000, x = 5,
           label = "<span style='color:grey70'> Avg. Monthly<br> home sales",
           fill = NA, label.color = NA) +
  labs(
    title = "<span style='font-size:12pt'>Halmiton Home Prices</span>",
    subtitle = "<span style='font-size:10pt'>Month over Month Variability has been <span style='color:red'>increasing</span></span>"
  ) +
  theme(panel.background = element_blank(),
        legend.position = c(.85, 1.13),
        legend.title = element_text(size = 8),
        #legend.key = element_rect(color = "transparent", fill = NA),
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        axis.line.x = element_line(color = "grey70"),
        plot.title = element_markdown(hjust = 0),
        plot.subtitle = element_markdown(hjust = 0),
        legend.direction = "horizontal")

p2 <- sales_prepared %>% 
  ggplot(aes(number, profit, fill = profit)) +
  geom_col() +
  scale_fill_gradient2(high = "black",
                        mid = "grey80",
                        low = "red",
                        breaks = c(-0.057, 0, 0.095),
                        labels = c("-5.7%", 0, "9.4%"),
                        limits = c(-0.057, 0.095)) +
  scale_y_continuous(limits = c(-.1, .1),
                     labels = scales::percent_format(),
                     breaks = c(0)) +
  scale_x_continuous(limits = c(0, 36),
                     expand = c(0, 0)) +
  annotate(geom = "segment", linetype = 21, y = 0, yend = 0, x = 0, xend = 36 ) +
  annotate("richtext", x = 5, y = 0.09, 
           label = "<span style='color:grey70'>MoM % Change</span>", 
           fill = NA, label.color = NA) +
  theme(panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        axis.title = element_blank(),
        axis.line.x = element_line(color = "grey70"),
        legend.position = "none") 

# same as patchwork p1 / p2

# p1 <- ggplotGrob(p1)
# p2 <- ggplotGrob(p2)
# grid::grid.newpage()
# grid::grid.draw(rbind(p1, p2))


p1 / p2 
```

```{r}
ggsave("practice_2021_10_2.png")
```