---
title: "World_map"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(spData)
library(tidyverse)

default_font_color <- "#4e4d47"
default_background_color <- "#f5f5f2"
```

```{r}
library(haven) # for reading  dta data
library(countrycode) # for changing country code 
uhc <- read_dta("../UHC.dta")

uhc_new <- uhc %>% 
  mutate(iso2c = countrycode(uhc$iso3c, origin = 'iso3c', destination = 'iso2c'))

world_new <- world %>% 
  left_join(uhc_new, by = c("iso_a2" = "iso2c")) %>% 
  mutate(SCI_cat = case_when(SCI > 80 ~ '3',
                             50 < SCI & SCI <= 80 ~ '2',
                             SCI > 20 ~ '1',
                             T ~ NA_character_),
         CATA10_cat = case_when(CATA10 >= 10 ~ '1',
                                CATA10 >= 2 & CATA10 < 10 ~ '2',
                                CATA10 < 2 ~ '3',
                                T ~ NA_character_)) %>% 
  unite(group, CATA10_cat, SCI_cat, sep = '-', remove = FALSE) %>% 
  mutate(fill = case_when(group == '1-1' ~ '#ff1d00',
                          group == '1-2' ~ '#9c1b00',
                          group == '1-3' ~ '#001900',
                          group == '2-1' ~ '#ff9986',
                          group == '2-2' ~ '#9c9269',
                          group == '2-3' ~ '#00873b',
                          group == '3-1' ~ '#ffe8d9',
                          group == '3-2' ~ '#9cddaa',
                          group == '3-3' ~ '#00cc60',
                          T ~ 'grey',
                          #T ~ 'white',
                          ))

# ["#ffe8d9", "#9cddaa", "#00cc60", "#ff9986", "#9c9269", "#00873b", "#ff1d00", "#9c1b00", "#001900"]
# world_new %>% View()
# world_new %>% filter(is.na(SCI))

```

```{r}
theme_map <- function(...) {
  theme_minimal() +
  theme(
    text = element_text(
      # family = default_font_family,
                        color = default_font_color),
    # remove all axes
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    # add a subtle grid
    panel.grid.major = element_line(color = "#dbdbd9", size = 0.2),
    panel.grid.minor = element_blank(),
    # background colors
    plot.background = element_rect(fill = default_background_color,
                                   color = NA),
    panel.background = element_rect(fill = default_background_color,
                                    color = NA),
    legend.background = element_rect(fill = default_background_color,
                                     color = NA),
    # borders and margins
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    panel.border = element_blank(),
    panel.spacing = unit(c(-.1, 0.2, .2, 0.2), "cm"),
    # titles
    legend.title = element_text(size = 11),
    legend.text = element_text(size = 9, hjust = 0,
                               color = default_font_color),
    plot.title = element_text(size = 15, hjust = 0.5,
                              color = default_font_color),
    plot.subtitle = element_text(size = 10, hjust = 0.5,
                                 color = default_font_color,
                                 margin = margin(b = -0.1,
                                                 t = -0.1,
                                                 l = 2,
                                                 unit = "cm"),
                                 debug = F),
    # captions
    plot.caption = element_text(size = 7,
                                hjust = .5,
                                margin = margin(t = 0.2,
                                                b = 0,
                                                unit = "cm"),
                                color = "#939184"),
    ...
  )
}

```


```{r}
map <- ggplot(
  data = world_new
  ) +
  geom_sf(
    aes(
      fill = fill
    ),
    # use thin white stroke for municipalities
    color = "white",
    size = 0.1
  ) +
  scale_fill_identity() +
  theme_map()


legend <- ggplot() +
  geom_tile(
    data = world_new,
    mapping = aes(
      x = as.integer(SCI_cat),
      y = as.integer(CATA10_cat), # as.integer for deleting NA
      fill = fill)
  ) +
  scale_fill_identity() +
  # labs(x = expression(Higher~SCI ~ symbol('\256')),
  #      y = expression(Lower~CATA10 ~ symbol('\256'))) +
  labs(x = "SCI",
       y = "CATA10") +
  theme_map() +
  theme(
    axis.title = element_text(size = 6),
    panel.grid.major = element_blank()
  ) +
  annotate("text", x = c(1, 2, 3), y = 0.3, label = c(" > 20", " > 50", " > 80"), size = 2) + 
  annotate("text", x = 0.2, y = c(1, 2, 3), label = c(" \u2265 10%", " \u2265 2%", " < 2%"), size = 2, angle = -90) +
  coord_fixed() 
```

```{r}
library(ggtext)
map <- map +
  annotate("curve", 
           x = 70, xend = 30, 
           y = -30, yend = 15,
           curvature = .3, size = .4, 
           arrow = arrow(length = unit(0.01, "npc"))) +
  annotate("richtext", 
           x = 50, y = -38, 
           label = "<span style='color:#ff1d00'>**These areas**</span> indicate <br> low SCI and <br> high CATA10",
           fill = NA, label.color = NA, 
           size = 3, hjust = 0) + 
  annotate("curve", 
           x = 140, xend = 100, 
           y = 20, yend = 35,
           curvature = .3, size = .4, 
           arrow = arrow(length = unit(0.01, "npc"))) + 
   annotate("richtext", 
            x = 140, y = 20, 
            label = "<span style='color:#001900'>**These areas**</span> indicate <br> high SCI and <br> high CATA10", 
            fill = NA, label.color = NA, 
            size = 3, hjust = 0) + 
  annotate("curve",
           x = -25, xend = 10, 
           y = 25, yend = 51,
           curvature = .3, size = .4, 
           arrow = arrow(length = unit(0.01, "npc"))) + 
   annotate("richtext", 
            x = -55, y = 25, 
            label = "<span style='color:#00cc60'>**These areas**</span> indicate <br> high SCI and <br> low CATA10", 
            fill = NA, label.color = NA, 
            size = 3, hjust = 0) +
  annotate("curve",
           x = -10, xend = 38,
           y = -50, yend = -15,
           curvature = .3, size = .4, 
           arrow = arrow(length = unit(0.01, "npc"))) +
   annotate("richtext", 
            x = -30, y = -58, 
            label = "<span style='color:#ffe8d9'>**These areas**</span> indicate <br> low SCI  and <br>low CATA10", 
            fill = NA, label.color = NA,
            size = 3, hjust = 0) +
    labs(x = "",
         y = "",
         title = "Service Coverage Index (SCI) and Share of Population \n with Catastrophic Health Spending at 10% threshold (CATA10)") +
    theme(plot.title = element_text(size = 14, color = "black"))


# world_new %>% filter(group == "1-3") %>% View()
```




```{r}
library(cowplot)
ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +
  draw_plot(legend, 
            x = 0.06, y = 0.24, 
            width = 0.2, height = 0.2)
```